require('core.options')
require('plugins-setup')
require('core.options')
require('core.keymaps')
require('plugins.lsp.lspconfig')
require('plugins.nvim-cmp')
require('plugins.lspkind')
require('plugins.gitsigns')
-- require('plugins.lsp.mason')
-- require('plugins.lsp.lspsaga')
